export type BiText = { en: string; hi: string }
export const t = (text: BiText, lang: 'en' | 'hi') => text[lang]

export const content = {
  nav: {
    logo:      { en: 'Prem Murti Sanjay Krishna Mishra', hi: 'प्रेम मूर्ति संजय कृष्ण मिश्रा' },
    about:     { en: 'About',     hi: 'परिचय' },
    events:    { en: 'Events',    hi: 'आयोजन' },
    media:     { en: 'Media',     hi: 'मीडिया' },
    gallery:   { en: 'Gallery',   hi: 'गैलरी' },
    astrology: { en: 'Astrology', hi: 'ज्योतिष' },
    contact:   { en: 'Contact',   hi: 'संपर्क' },
    bookNow:   { en: 'Book Now',  hi: 'बुकिंग करें' },
  },
  hero: {
    label:    { en: 'Katha & Astrology', hi: 'कथा और ज्योतिष' },
    headline: { en: 'Spreading Wisdom Through Sacred Katha & Divine Astrology', hi: 'पवित्र कथा और दिव्य ज्योतिष के माध्यम से ज्ञान का प्रसार' },
    sub:      { en: 'A revered spiritual orator and Vedic astrologer, Prem Murti Sanjay Krishna Mishra guides devotees toward clarity, dharma, and inner peace through his transformative kathas and precise astrological wisdom.', hi: 'एक पूजनीय आध्यात्मिक वक्ता और वैदिक ज्योतिषी, प्रेम मूर्ति संजय कृष्ण मिश्रा अपनी कथाओं और सटीक ज्योतिषीय ज्ञान के माध्यम से भक्तों को स्पष्टता, धर्म और आंतरिक शांति की ओर मार्गदर्शन करते हैं।' },
    cta1:     { en: 'Book a Katha', hi: 'कथा बुक करें' },
    cta2:     { en: 'Watch Pravachan', hi: 'प्रवचन देखें' },
  },
  about: {
    label:       { en: 'Our Journey', hi: 'हमारा परिचय' },
    heading:     { en: 'A Lifetime Dedicated to Devotion', hi: 'भक्ति को समर्पित एक जीवन' },
    p1:          { en: 'Prem Murti Sanjay Krishna Mishra is a revered katha vachak and Vedic astrologer based in Tryambakeshwar (Nashik) and Jabalpur. With decades of devoted service, he has performed 551 Shrimad Bhagavat Kathas, 240 Shiv Mahapurans, 147 Ram Kathas, and 112 Shrimad Devi Bhagavat Mahapurans across India.', hi: 'प्रेम मूर्ति संजय कृष्ण मिश्रा एक पूजनीय कथा वाचक और वैदिक ज्योतिषी हैं, जो त्र्यंबकेश्वर (नाशिक) और जबलपुर में आधारित हैं। दशकों की समर्पित सेवा के साथ, उन्होंने भारत भर में 551 श्रीमद् भागवत कथाएं, 240 शिव महापुराण, 147 राम कथाएं और 112 श्रीमद् देवी भागवत महापुराण का आयोजन किया है।' },
    p2:          { en: "As a Vedic astrologer, he offers deep insight into kundali reading, vastu shastra, and life guidance — helping families navigate life's milestones with divine clarity.", hi: 'एक वैदिक ज्योतिषी के रूप में, वे कुंडली पाठन, वास्तु शास्त्र और जीवन मार्गदर्शन में गहरी अंतर्दृष्टि प्रदान करते हैं — परिवारों को दिव्य स्पष्टता के साथ जीवन के महत्वपूर्ण क्षणों में मार्गदर्शन करते हैं।' },
    readMore:    { en: 'Read More', hi: 'और पढ़ें' },
    photo_quote: { en: '"Where devotion meets wisdom, the divine reveals itself."', hi: '"जहाँ भक्ति और ज्ञान मिलते हैं, वहाँ ईश्वर प्रकट होते हैं।"' },
    stats: [
      { value: '551', label: { en: 'Shrimad Bhagavat Katha', hi: 'श्रीमद् भागवत कथा' } },
      { value: '240', label: { en: 'Shiv Mahapuran',          hi: 'शिव महापुराण' } },
      { value: '147', label: { en: 'Ram Katha',               hi: 'राम कथा' } },
      { value: '112', label: { en: 'Devi Bhagavat Mahapuran', hi: 'देवी भागवत महापुराण' } },
    ],
  },
  services: {
    label:   { en: 'Our Services', hi: 'हमारी सेवाएँ' },
    heading: { en: 'How We Can Serve You', hi: 'हम आपकी कैसे सेवा कर सकते हैं' },
    items: [
      { icon: 'menu_book',           image: '/images/services/bhagavat-katha.jpg',
        title: { en: 'Shrimad Bhagavat Katha', hi: 'श्रीमद् भागवत कथा' },
        desc:  { en: 'The sacred discourse on Shrimad Bhagavat Purana — awakening devotion, wisdom, and liberation through the divine stories of Lord Vishnu.', hi: 'श्रीमद् भागवत पुराण पर पवित्र प्रवचन — भगवान विष्णु की दिव्य कथाओं के माध्यम से भक्ति, ज्ञान और मोक्ष की जागृति।' },
        cta:   { en: 'Book Katha', hi: 'कथा बुक करें' } },
      { icon: 'temple_hindu',         image: '/images/services/ram-katha.jpg',
        title: { en: 'Shri Ram Katha', hi: 'श्री राम कथा' },
        desc:  { en: 'A soul-stirring narration of the Ramayana — the divine journey of Lord Ram that inspires righteousness, devotion, and the triumph of good over evil.', hi: 'रामायण की आत्मा को छूने वाली कथा — भगवान राम की दिव्य यात्रा जो धर्म, भक्ति और सत्य की जीत को प्रेरित करती है।' },
        cta:   { en: 'Book Katha', hi: 'कथा बुक करें' } },
      { icon: 'brightness_5',         image: '/images/services/shiv-mahapuran.jpg',
        title: { en: 'Shiv Mahapuran', hi: 'शिव महापुराण' },
        desc:  { en: 'The great Purana of Lord Shiva — revealing the mysteries of creation, the glory of Mahadev, and the path to moksha through Shiva\'s divine grace.', hi: 'भगवान शिव का महापुराण — सृष्टि के रहस्यों, महादेव की महिमा और शिव की दिव्य कृपा से मोक्ष के मार्ग का वर्णन।' },
        cta:   { en: 'Book Katha', hi: 'कथा बुक करें' } },
      { icon: 'self_improvement',      image: '/images/services/mahamritunjay.jpg',
        title: { en: 'Mahamritunjay Jap', hi: 'महामृत्युंजय जाप' },
        desc:  { en: 'The powerful Mahamritunjay mantra jap performed for health, protection, longevity, and liberation from fear — a profound Vedic remedy.', hi: 'स्वास्थ्य, सुरक्षा, दीर्घायु और भय से मुक्ति के लिए महामृत्युंजय मंत्र जाप — एक गहरा वैदिक उपाय।' },
        cta:   { en: 'Book Jap', hi: 'जाप बुक करें' } },
      { icon: 'auto_awesome',          image: '/images/services/kal-sarp.jpg',
        title: { en: 'Kal Sarp Yog Shanti', hi: 'काल सर्प योग की शांति' },
        desc:  { en: 'Sacred Kal Sarp Dosh Shanti puja at Tryambakeshwar — the most powerful remedy for removing obstacles caused by this rare planetary combination.', hi: 'त्र्यंबकेश्वर में काल सर्प दोष शांति पूजा — इस दुर्लभ ग्रह संयोग से उत्पन्न बाधाओं को दूर करने का सबसे शक्तिशाली उपाय।' },
        cta:   { en: 'Book Puja', hi: 'पूजा बुक करें' } },
      { icon: 'local_fire_department', image: '/images/services/puja-anusthan.jpg',
        title: { en: 'Puja & Anusthan', hi: 'पूजा और अनुष्ठान' },
        desc:  { en: 'Special yagnas, griha pravesh puja, satyanarayan katha, and sacred ceremonies performed with complete Vedic rituals.', hi: 'विशेष यज्ञ, गृह प्रवेश पूजा, सत्यनारायण कथा और पूर्ण वैदिक विधि-विधान के साथ पवित्र समारोह।' },
        cta:   { en: 'Book Puja', hi: 'पूजा बुक करें' } },
    ],
  },
  events: {
    label:    { en: 'Upcoming Kathas', hi: 'आगामी कथाएं' },
    heading:  { en: 'Join Us in Sacred Gatherings', hi: 'पवित्र सभाओं में हमारे साथ जुड़ें' },
    sub:      { en: 'Join these sacred gatherings of wisdom and divinity across holy lands.', hi: 'पवित्र भूमियों पर ज्ञान और दिव्यता की इन पवित्र सभाओं में शामिल हों।' },
    register: { en: 'Register Now', hi: 'अभी पंजीकरण करें' },
    items: [
      { dates: '12 - 18 OCT', image: '/images/events/bhagavat-event.jpg', title: { en: 'Bhagavat Katha', hi: 'भागवत कथा' }, location: { en: 'Tryambakeshwar, Nashik', hi: 'त्र्यंबकेश्वर, नाशिक' } },
      { dates: '05 - 11 NOV', image: '/images/events/ram-event.jpg',      title: { en: 'Ram Katha',      hi: 'राम कथा' },     location: { en: 'Jabalpur, MP',          hi: 'जबलपुर, मध्यप्रदेश' } },
      { dates: '20 - 26 DEC', image: '/images/events/shiv-event.jpg',     title: { en: 'Shiv Purana',    hi: 'शिव पुराण' },   location: { en: 'Nashik, Maharashtra',   hi: 'नाशिक, महाराष्ट्र' } },
    ],
  },
  quote: {
    text: { en: '"Realizing the divinity within is the ultimate purpose of human existence. When we surrender our ego at the lotus feet of the Lord, our journey toward eternal bliss begins."', hi: '"अपने भीतर की दिव्यता को पहचानना मानव जीवन का परम उद्देश्य है। जब हम अपना अहंकार प्रभु के चरण कमलों में अर्पण करते हैं, तब शाश्वत आनंद की ओर हमारी यात्रा शुरू होती है।"' },
    attr: { en: '— Prem Murti Sanjay Krishn Mishra', hi: '— प्रेम मूर्ति संजय कृष्ण मिश्रा' },
  },
  media: {
    label:   { en: 'Digital Satsang', hi: 'डिजिटल सत्संग' },
    heading: { en: 'Watch & Listen',  hi: 'देखें और सुनें' },
    sub:     { en: 'Listen to the latest discourses and divine kathas.', hi: 'नवीनतम प्रवचन और दिव्य कथाएं सुनें।' },
    youtube: { en: 'View YouTube Channel', hi: 'यूट्यूब चैनल देखें' },
    videos: [
      { title: { en: 'Shrimad Bhagavat Katha', hi: 'श्रीमद् भागवत कथा' }, sub: { en: 'Prem Murti Sanjay Krishna Mishra', hi: 'प्रेम मूर्ति संजय कृष्ण मिश्रा' }, youtubeId: '1h9PoIhWgI8' },
      { title: { en: 'Katha Pravachan',        hi: 'कथा प्रवचन' },         sub: { en: 'Prem Murti Sanjay Krishna Mishra', hi: 'प्रेम मूर्ति संजय कृष्ण मिश्रा' }, youtubeId: 'yLgR1BO98J8' },
      { title: { en: 'Bhagavat Katha Saptah',  hi: 'भागवत कथा सप्ताह' },  sub: { en: 'Prem Murti Sanjay Krishna Mishra', hi: 'प्रेम मूर्ति संजय कृष्ण मिश्रा' }, youtubeId: 'cOEqTykLzpQ' },
      { title: { en: 'Spiritual Discourse',    hi: 'आध्यात्मिक प्रवचन' }, sub: { en: 'Prem Murti Sanjay Krishna Mishra', hi: 'प्रेम मूर्ति संजय कृष्ण मिश्रा' }, youtubeId: 'PlAnHRW3WPU' },
    ],
  },
  gallery: {
    label:   { en: 'Gallery',         hi: 'गैलरी' },
    heading: { en: 'Moments of Grace', hi: 'कृपा के क्षण' },
    viewAll: { en: 'View All',         hi: 'सभी देखें' },
  },
  contact: {
    label:   { en: 'Connect with Us', hi: 'हमसे जुड़ें' },
    heading: { en: 'Inquire for a Katha', hi: 'कथा के लिए पूछताछ करें' },
    sub:     { en: 'Whether for a private family event or a large community gathering, we are here to bring the divine word to your space.', hi: 'चाहे एक निजी पारिवारिक कार्यक्रम हो या एक बड़ी सामुदायिक सभा, हम दिव्य वचन को आपके स्थान तक लाने के लिए यहाँ हैं।' },
    phone1:  '+91 76974 17882',
    phone2:  '+91 76974 17882',
  },
  footer: {
    logo:      { en: 'Prem Murti Sanjay Krishna Mishra', hi: 'प्रेम मूर्ति संजय कृष्ण मिश्रा' },
    quote:     { en: '"May the divine grace of peace and love be with you always."', hi: '"शांति और प्रेम की दिव्य कृपा सदा आपके साथ रहे।"' },
    copyright: { en: '© 2026 Prem Murti Sanjay Krishna Mishra. All rights reserved.', hi: '© 2026 प्रेम मूर्ति संजय कृष्ण मिश्रा। सर्वाधिकार सुरक्षित।' },
    links: [
      { en: 'About',          hi: 'परिचय',            href: '#about' },
      { en: 'Contact',        hi: 'संपर्क',           href: '#contact' },
      { en: 'Privacy Policy', hi: 'गोपनीयता नीति',   href: '#' },
    ],
  },
}
